### ISSUE TITLE
我不能用外置登录&不能下载of&更改鼠标报错

### ISSUE THREAD

**Issue by Airnp** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#111]
of报错
java.io.IOException: Unable to download from https://download.mcbbs.net/v1/packages/f3c4aa96e12951cd2781b3e1c0e8ab82bf719cf2/1.16.json
	at net.kdt.pojavlaunch.utils.DownloadUtils.download(DownloadUtils.java:39)
	at net.kdt.pojavlaunch.utils.DownloadUtils.download(DownloadUtils.java:20)
	at net.kdt.pojavlaunch.utils.DownloadUtils.downloadFile(DownloadUtils.java:61)
	at net.kdt.pojavlaunch.mirrors.DownloadMirror.downloadFileMirrored(DownloadMirror.java:66)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader.lambda$downloadAssetsIndex$2(MinecraftDownloader.java:175)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$$ExternalSyntheticLambda2.call(Unknown Source:4)
	at net.kdt.pojavlaunch.utils.DownloadUtils.downloadFile(DownloadUtils.java:125)
	at net.kdt.pojavlaunch.utils.DownloadUtils.ensureSha1(DownloadUtils.java:147)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader.downloadAssetsIndex(MinecraftDownloader.java:172)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader.downloadAndProcessMetadata(MinecraftDownloader.java:210)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader.downloadGame(MinecraftDownloader.java:90)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader.lambda$start$0$net-kdt-pojavlaunch-tasks-MinecraftDownloader(MinecraftDownloader.java:63)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$$ExternalSyntheticLambda0.run(Unknown Source:10)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: javax.net.ssl.SSLPeerUnverifiedException: Hostname download.mcbbs.net not verified:
    certificate: sha1/1I9eVoq1soOLrB5EinqFbU4nNgY=
    DN: CN=*.cdn.myqcloud.com
    subjectAltNames: [*.cdn.myqcloud.com, *.2144.cn, *.2144.com, *.4399.com, *.5054399.com, *.58cdn.com.cn, *.danmu.com, *.dianping.com, *.dpfile.com, *.ffnews.cn, *.file.myqcloud.com, *.flash.2144.com, *.flash.cn, *.image.myqcloud.com, *.img4399.com, *.meituan.net, *.mykeeta.net, *.sogoucdn.com, *.uniqlo.cn, *.vip.cdngot.com, *.vod.myqcloud.com, *.vod2.myqcloud.com, *.wanyabox.com, *.zhongcheng818.com, *.zservey.net, cdn.myqcloud.com, nitrome.com.4399.com, www.miniclip.com.4399pk.com, xpdl999.aiwan4399.com]
	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:198)
	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(Unknown Source:0)
	at net.kdt.pojavlaunch.utils.DownloadUtils.download(DownloadUtils.java:31)
	... 15 more

外置登录报错
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.endsWith(java.lang.String)' on a null object reference
	at com.externallogin.login.OtherLoginApi.setBaseUrl(OtherLoginApi.java:24)
	at com.externallogin.fragments.OtherLoginFragment.lambda$onViewCreated$7$com-externallogin-fragments-OtherLoginFragment(OtherLoginFragment.java:179)
	at com.externallogin.fragments.OtherLoginFragment$$ExternalSyntheticLambda9.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764）

**Comment by Vera-Firefly** [comment]
一看就是从来不关注MCBBS等论坛的,MCBBS寄了,切换官方源解决
对于皮肤站,你要确保你提供的为正确的yggdrasil地址,
启动器内置的修改鼠标图标仅支持.jpg和.png格式
