### ISSUE TITLE
[BUG] <Short description>无法加载1.8forge

### ISSUE THREAD

**Issue by xguan744** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#174]
### Describe the bug

不能加载

### The log file and images/videos

![Screenshot_20240325_233004_net kdt pojavlaunch firefly debug](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/128487904/23e0e5f0-fb4d-4d0d-b181-7dc81928480f)
[latestlog.txt](https://github.com/Vera-Firefly/Pojav-Glow-Worm/files/14746083/latestlog.txt)

### Steps To Reproduce

```markdown
java.lang.NumberFormatException: For input string: "8-forge1"
	at java.lang.Integer.parseInt(Integer.java:615)
	at java.lang.Integer.parseInt(Integer.java:650)
	at net.kdt.pojavlaunch.profiles.ProfileLanguageSelector.getLanguage(ProfileLanguageSelector.java:240)
	at net.kdt.pojavlaunch.profiles.ProfileLanguageSelector.languageChangers(ProfileLanguageSelector.java:261)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:353)
	at net.kdt.pojavlaunch.MainActivity.lambda$initLayout$4$net-kdt-pojavlaunch-MainActivity(MainActivity.java:208)
	at net.kdt.pojavlaunch.MainActivity$$ExternalSyntheticLambda14.isReady(Unknown Source:6)
	at net.kdt.pojavlaunch.MinecraftGLSurface.lambda$realStart$1$net-kdt-pojavlaunch-MinecraftGLSurface(MinecraftGLSurface.java:612)
	at net.kdt.pojavlaunch.MinecraftGLSurface$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:929)
```

### Expected Behavior

希望加载1.8forge

### Platform

```markdown
- Device model: 荣耀9x pro
- CPU architecture: arm64
- Android version: 10
- PojavLauncher version: edelweiss-20240318-b179336-exp_v3
```

**Comment by Vera-Firefly** [comment]
似乎给出了错误的标识符,你确定你所使用的是正确格式的吗?

**Comment by xguan744** [comment]
> 似乎给出了错误的标识符,你确定你所使用的是正确格式的吗?

标识符是什么意思 (我的设置都是默认的)

**Comment by Vera-Firefly** [comment]
> > 似乎给出了错误的标识符,你确定你所使用的是正确格式的吗?
> 
> 标识符是什么意思 (我的设置都是默认的)

这与游戏外语言选择功能有关,你给出的"8-forge1"中的"-"是语言选择功能无法识别的字符,导致的错误发生

**Comment by Vera-Firefly** [comment]
尝试把游戏语言选择都设为默认(跟随游戏选择)
