### ISSUE TITLE
[BUG] JDK 21.0.4 is cropped

### ISSUE THREAD

**Issue by xbxct** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#228]
### Describe the bug

headless JDK 21.0.4 in the new release is a cropped bad version, which causes crashes.

### The log file and images/videos

---- Crashed! ----
Date/Time: 2024/05/26 10:46:07.2966
Quilt Loader Version: 0.25.0

-- Crash --

org.quiltmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'faster-random'!
	at org.quiltmc.loader.impl.QuiltLoaderImpl.invokePreLaunch(QuiltLoaderImpl.java:1231)
	at org.quiltmc.loader.impl.launch.knot.Knot.init(Knot.java:175)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:78)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'faster-random'!
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:66)
	at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:34)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:64)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:49)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at org.quiltmc.loader.impl.QuiltLoaderImpl.invokePreLaunch(QuiltLoaderImpl.java:1229)
	... 3 more
Caused by: java.lang.ExceptionInInitializerError
	at com.github.anopensaucedev.fasterrandom.FasterRandomPrelaunch.onPreLaunch(FasterRandomPrelaunch.java:18)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:36)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:62)
	... 6 more
Caused by: java.lang.IllegalArgumentException: No implementation of the random number generator algorithm "L64X128MixRandom" is available
	at java.base/java.util.random.RandomGeneratorFactory.findProvider(RandomGeneratorFactory.java:229)
	at java.base/java.util.random.RandomGeneratorFactory.factoryOf(RandomGeneratorFactory.java:275)
	at java.base/java.util.random.RandomGeneratorFactory.of(RandomGeneratorFactory.java:360)
	at com.github.anopensaucedev.fasterrandom.FasterRandom.<clinit>(FasterRandom.java:21)
	... 9 more

### Steps To Reproduce

```markdown
Launching minecraft with JDK internal 21 21.0.4
```

### Expected Behavior

Running the game without crashing.

### Platform

```markdown
- Device model:Xiaomi Redmi 10C
- CPU architecture:4x Qualcomm Kryo 265 LP @ 1900 МГц
4x ARM Cortex-A73 @ 2400 МГц
- Android version:13 (Tiramisu)
- PojavLauncher version:edelweiss-20240525-36bee5f-exp_v3
```

**Comment by Vera-Firefly** [comment]
Confirm that your version of QuiltMC is compatible with the Minecraft version
Recommend reloading your Quilt loader

**Comment by xboct02** [comment]
Everything works on JDK 21.0.1 without errors. Quilt does not cause errors.

**Comment by AnOpenSauceDev** [comment]
Creator of Faster Random here (i lurk for these bugs), Quilt is not the problem here. I'm not sure if your launcher auto-downloads JRE's, but using a "headless" JRE makes Minecraft crash with this mod. If you can, use a non-headless JRE which exposes Faster Random to the much faster new random systems that it requires access to.

**Comment by xbxct** [comment]
I remember that headless flashed in the crash log, but it doesn't matter, it's just that faster random can't find a random number generator in this newest version.

**Comment by AnOpenSauceDev** [comment]
Headless tends to be the most common reason that a JDK doesn't work with Faster Random, but it could also just be due to a poor JDK.

**Comment by Vera-Firefly** [comment]
Okay, I think I know something. I'll work it out later

**Comment by xbxct** [comment]
Victory

**Comment by Vera-Firefly** [comment]
![Screenshot_2024-06-08-16-43-51-241_com huawei browser](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/87926662/6e2a191a-3000-495e-ab65-aa96013b4d63)
Now I want to know one thing, how did you come up with this question?

**Comment by Vera-Firefly** [comment]
Attribute `-Djava.awt.headless=false` has already been added here

**Comment by AnOpenSauceDev** [comment]
Whether java has the property of headless or not is not the problem. There is a variant of JDK that is usually called "headless" that causes this crash. Either that, or the JDK used is too old/doesn't support the feature.

**Comment by Vera-Firefly** [comment]
> Whether java has the property of headless or not is not the problem. There is a variant of JDK that is usually called "headless" that causes this crash. Either that, or the JDK used is too old/doesn't support the feature.

The JRE I'm using here is always up to date, which is probably why

**Comment by Vera-Firefly** [comment]
You can wait a week before taking the test.

**Comment by Vera-Firefly** [comment]
Or fork my repository and build a general release of my own, like 21.0.3
https://github.com/Vera-Firefly/android-openjdk-build

**Comment by AnOpenSauceDev** [comment]
Using the latest JDK should be fine, in that case this feature might just not exist for android.

**Comment by Vera-Firefly** [comment]
> Using the latest JDK should be fine, in that case this feature might just not exist for android.

I can't fix it if it doesn't exist in android

**Comment by AnOpenSauceDev** [comment]
Again, no clue if it is or isn't. It _should_ be included, but recently that has become painfully obvious that it's mostly not for most JVM's.

**Comment by xbxct** [comment]
Conclusion: the jvm is working, but not full-fledged, this leads to some incompatibility problems, but since everything runs in the emulator, android does not affect its stable operation. Most likely, some components have been changed for certain needs of the publisher.

**Comment by xbxct** [comment]
The headless parameter does not affect this and the problem lies elsewhere, just someone cut out part of the code (optimized).

**Comment by aaaapai** [comment]
Now that the issue is resolved, an update will be pushed to jdk17, 21 soon.
https://github.com/aaaapai/android-openjdk-build/actions/runs/9817708888
