### ISSUE TITLE
I keep getting this error since I updated

### ISSUE THREAD

**Issue by 44cK3r** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#304]
### Describe the bug

Every time I launch the app I get this:

java.lang.RuntimeException: Bad Request
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.getResponseThrowable(MicrosoftBackgroundLogin.java:351)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.acquireAccessToken(MicrosoftBackgroundLogin.java:152)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:77)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16990676/latestlog.txt)
![Screenshot_2024-09-13-18-18-42-29_405a2fc07b254ef5ee3229f4fec175cf](https://github.com/user-attachments/assets/058ef4ae-80cd-45b2-a42a-065498ff5061)
![Screenshot_2024-09-13-18-18-50-00_405a2fc07b254ef5ee3229f4fec175cf](https://github.com/user-attachments/assets/13d7ff6a-6af9-4667-8360-067c410af64d)
![Screenshot_2024-09-13-18-18-56-44_405a2fc07b254ef5ee3229f4fec175cf](https://github.com/user-attachments/assets/527106f9-00aa-4ca9-a0e3-9509504de2e9)

### Steps To Reproduce

```markdown
1. Launch the app
```

### Expected Behavior

I expected no error at launch

### Platform

```markdown
- Device model: CPH2305
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: fuchsia-20240908-b2713db-main-v3
```

**Comment by Coloryr** [comment]
Remove your `Microsoft account` and relogin it.

**Comment by 44cK3r** [comment]
Ok

**Comment by 44cK3r** [comment]
It worked thank you so very much
